import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Header } from "../components/layout/header";
import { Footer } from "../components/layout/footer";
import { Geologica } from "next/font/google";
import { AuthProvider } from "@/context/AuthProvider";
import EmployerProvider from "@/context/EmployerProvider";
import CategoryProvider from "@/context/CategoryProvider";
import SkillProvider from "@/context/SkillProvider";
import FreelancerProvider from "@/context/FreelancerProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const geologica = Geologica({
  subsets: ["latin", "cyrillic"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geologica.className}>
      <body className={`antialiased`}>
        <AuthProvider>
          <FreelancerProvider>
            <EmployerProvider>
              <CategoryProvider>
                <SkillProvider>
                  <Header />
                  {children}
                  <Footer />
                  <ToastContainer />
                </SkillProvider>
              </CategoryProvider>
            </EmployerProvider>
          </FreelancerProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
